# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

PROJECT_NAME = "YakVernac"
XCODE_PROJECT = "./ios/#{PROJECT_NAME}.xcodeproj"
XCODE_WORKSPACE = "./ios/#{PROJECT_NAME}.xcworkspace"
OUTPUT_DIRECTORY = "./fastlane/builds"
IPA_DIRECTORY = "#{OUTPUT_DIRECTORY}/#{PROJECT_NAME}.ipa"
# TESTERS_FILE = "./fastlane/testers.txt"
BUILD_FOR_DEVELOPMENT_ONLY = false # true = Build for Development | false = Build to create a release
BUILD_ONLY = true

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  private_lane :build do
    configuration_name = "Release"
    export_options_method = "development"
    code_sign_identity = "iPhone Developer"
    MY_APP_ID = "com.yakvernac.yakvernac"
    MY_PROFILE = "match Development com.yakvernac.yakvernac"
    MY_TEAM = "UY8K48LB7X"
    
    increment_build_number(xcodeproj: XCODE_PROJECT)
    
    increment_version_number(
      bump_type: "patch",
      xcodeproj: XCODE_PROJECT,
    )

    settings_to_override = {
      :BUNDLE_IDENTIFIER => "com.yakvernac.yakvernac",
      :PROVISIONING_PROFILE_SPECIFIER => "Yakvernac_Distribution",
      :DEVELOPMENT_TEAM => "Nathan Wennerbom",
    }

    create_keychain(
      name: "Keychain",
      password: "naxtre",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    match(
      app_identifier: "com.yakvernac.yakvernac",
      git_url: "https://github.com/YakVernac/react-native.git",
      type: "development",
      username: "1546721654",
      team_id: "UY8K48LB7X",
      keychain_name: "Keychain",
      keychain_password: "naxtre",
      readonly: true
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: XCODE_PROJECT,
      code_sign_identity: code_sign_identity,
      bundle_identifier: "com.yakvernac.yakvernac",
      "profile_name": "Yakvernac_Distribution"
    )

    gym(
      scheme: PROJECT_NAME,
      workspace: XCODE_WORKSPACE,
      silent: true,
      configuration: configuration_name,
      xcargs: `#{settings_to_override} -UseNewBuildSystem=YES`,
      output_directory: OUTPUT_DIRECTORY,
      output_name: "#{PROJECT_NAME}.ipa",
      export_options: {
        method: "development",
        signingStyle: "manual",
        provisioningProfiles: { 
            com.yakvernac.yakvernac => "Yakvernac_Distribution"
        }
      }
    )

  end
  desc "Create Signed IPA Build"
  lane :beta do
    build
  end
end
